### PR TITLE
Add SendWithContext()

### PR DESCRIPTION
**Pull request by lamanotrama**
Refactoring and testing would be needed.

### CODE REVIEW

**Comment by lamanotrama** [comment]
Sorry I can't think of a good implementation to make this DRY 🙇

**Comment by lamanotrama** [comment]
Tweaked! Please review!

**Comment by mash** [comment]
I just found https://github.com/natureglobal/firequeue/tree/context 🙄

**Comment by lamanotrama** [comment]
Oh!

**Review by mash — APPROVED** [review]
Looks good 👍

**Pull request merged**
